/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasipenghitungkata;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

public class AplikasiPenghitungKata extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiPenghitungKata
     */
    public AplikasiPenghitungKata() {
        initComponents();
          // Menambahkan DocumentListener untuk menghitung secara real-time
        inputTextArea.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                perbaruiPerhitungan();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                perbaruiPerhitungan();
            }
             @Override
            public void changedUpdate(DocumentEvent e) {
                perbaruiPerhitungan();
            }
        
    });
    }
   
//    Method untuk memperbarui perhitungan jumlah kata, karakter, kalimat, dan paragraf
    private void perbaruiPerhitungan() {
        String teks = inputTextArea.getText();

        int jumlahKata = teks.isEmpty() ? 0 : teks.trim().split("\\s+").length;
        int jumlahKarakter = teks.length();
        int jumlahKalimat = teks.split("[.!?]").length;
        int jumlahParagraf = teks.split("\n").length;

        labelJumlahKata.setText("Jumlah Kata: " + jumlahKata);
        labelJumlahKarakter.setText("Jumlah Karakter: " + jumlahKarakter);
        labelJumlahKalimat.setText("Jumlah Kalimat: " + jumlahKalimat);
        labelJumlahParagraf.setText("Jumlah Paragraf: " + jumlahParagraf);
    }
    
    
    // Method untuk mencari kata tertentu dalam teks
    private void cariKata() {
        String teks = inputTextArea.getText();
        String kataDicari = cariTextField.getText();
        int jumlahKemunculan = 0;

        if (!kataDicari.isEmpty()) {
            String[] kataArray = teks.split("\\s+");
            for (String kata : kataArray) {
                if (kata.equalsIgnoreCase(kataDicari)) {
                    jumlahKemunculan++;
                }
            }
        }

        labelHasilPencarian.setText("Kemunculan '" + kataDicari + "': " + jumlahKemunculan);
    }

    // Method untuk menyimpan teks dan hasil perhitungan ke dalam file
    private void simpanKeFile() {
        String teks = inputTextArea.getText();
        String hasilPerhitungan = 
            "Jumlah Kata: " + labelJumlahKata.getText() + "\n" +
            "Jumlah Karakter: " + labelJumlahKarakter.getText() + "\n" +
            "Jumlah Kalimat: " + labelJumlahKalimat.getText() + "\n" +
            "Jumlah Paragraf: " + labelJumlahParagraf.getText();

        try (BufferedWriter writer = new BufferedWriter(new FileWriter("hasil_penghitungan.txt"))) {
            writer.write("Teks:\n" + teks + "\n\nHasil Perhitungan:\n" + hasilPerhitungan);
            JOptionPane.showMessageDialog(this, "Teks dan hasil perhitungan berhasil disimpan ke file.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan ke file.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelJudul = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputTextArea = new javax.swing.JTextPane();
        labelJumlahKata = new javax.swing.JLabel();
        labelJumlahKarakter = new javax.swing.JLabel();
        labelJumlahKalimat = new javax.swing.JLabel();
        labelJumlahParagraf = new javax.swing.JLabel();
        tombolHitung = new javax.swing.JButton();
        tombolSimpan = new javax.swing.JButton();
        tombolCari = new javax.swing.JButton();
        cariTextField = new javax.swing.JTextField();
        labelHasilPencarian = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelJudul.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJudul.setText("APLIKASI PENGHITUNG KATA");
        labelJudul.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelJudul, java.awt.BorderLayout.PAGE_START);
        labelJudul.getAccessibleContext().setAccessibleDescription("");

        jPanel1.setToolTipText("");
        jPanel1.setLayout(new java.awt.GridBagLayout());

        inputTextArea.setMinimumSize(new java.awt.Dimension(200, 100));
        inputTextArea.setPreferredSize(new java.awt.Dimension(100, 200));
        jScrollPane1.setViewportView(inputTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 37, 0, 0);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        labelJumlahKata.setText("Jumlah Kata");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 37, 0, 0);
        jPanel1.add(labelJumlahKata, gridBagConstraints);

        labelJumlahKarakter.setText("Jumlah Karakter");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 37, 0, 0);
        jPanel1.add(labelJumlahKarakter, gridBagConstraints);

        labelJumlahKalimat.setText("Jumlah Kalimat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 37, 0, 0);
        jPanel1.add(labelJumlahKalimat, gridBagConstraints);

        labelJumlahParagraf.setText("Jumlah Paragraf");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 37, 0, 0);
        jPanel1.add(labelJumlahParagraf, gridBagConstraints);

        tombolHitung.setText("Hitung");
        tombolHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHitungActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 27, 0, 27);
        jPanel1.add(tombolHitung, gridBagConstraints);

        tombolSimpan.setText("Simpan");
        tombolSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolSimpanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        jPanel1.add(tombolSimpan, gridBagConstraints);

        tombolCari.setText("Cari");
        tombolCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolCariActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        jPanel1.add(tombolCari, gridBagConstraints);

        cariTextField.setPreferredSize(new java.awt.Dimension(100, 22));
        cariTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 64;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.insets = new java.awt.Insets(17, 37, 1, 0);
        jPanel1.add(cariTextField, gridBagConstraints);

        labelHasilPencarian.setText("Hasil Pencarian");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 37, 15, 0);
        jPanel1.add(labelHasilPencarian, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariTextFieldActionPerformed

    }//GEN-LAST:event_cariTextFieldActionPerformed

    private void tombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolSimpanActionPerformed
        simpanKeFile();
    }//GEN-LAST:event_tombolSimpanActionPerformed

    private void tombolHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHitungActionPerformed
     perbaruiPerhitungan();
    }//GEN-LAST:event_tombolHitungActionPerformed

    private void tombolCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCariActionPerformed
      cariKata();
    }//GEN-LAST:event_tombolCariActionPerformed

     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPenghitungKata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cariTextField;
    private javax.swing.JTextPane inputTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelHasilPencarian;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelJumlahKalimat;
    private javax.swing.JLabel labelJumlahKarakter;
    private javax.swing.JLabel labelJumlahKata;
    private javax.swing.JLabel labelJumlahParagraf;
    private javax.swing.JButton tombolCari;
    private javax.swing.JButton tombolHitung;
    private javax.swing.JButton tombolSimpan;
    // End of variables declaration//GEN-END:variables
}
